[project]
name = "my-resume"
version = "0.1.0"
description = "Olivier Philippon's ~over-engineered~ hand-crafted resume 🤓"
authors = [{ name = "Olivier Philippon", email = "olivier@dunsap.com" }]
requires-python = ">=3.12,<4"
readme = "README.md"
dependencies = [
    "django>=5.0.3,<6",
    "django-tailwind-cli>=2.8.0,<3",
    "django-google-fonts>=0.0.3,<0.0.4",
    "playwright>=1.40.0,<2",
    "pillow>=10.3.0,<11",
]

[dependency-groups]
dev = [
    "mypy>=1.19.1,<2",
    "pre-commit>=3.6.0,<4",
    "ruff==0.15.0",
    "ipython>=8.19.0,<9",
    "django-browser-reload>=1.12.1,<2",
    "djlint>=1.36.4,<2",
]
deployment = ["ghp-import>=2.1.0,<3"]

[tool.uv]
package = false
default-groups = [
    "dev",
    "deployment",
]



[tool.mypy]
# @link https://mypy.readthedocs.io/en/stable/config_file.html#using-a-pyproject-toml
python_version = "3.12"
mypy_path = "myresume/"
[[tool.mypy.overrides]]
module = [
    "django.*",
    "djlint.*",
]
ignore_missing_imports = true

[tool.ruff]
exclude = [".venv"]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I"]
# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]

[tool.ruff.lint.isort]
combine-as-imports = true
extra-standard-library = ["tomllib"]
known-first-party = ["myresume"]

[tool.djlint]
max_line_length = 88
profile = "django"
ignore = "H019"
blank_line_after_tag="load,extends,include,endblock"
